jobs:
- name: hello-world-job
  plan:
  - task: hello-world-task
    config:
      platform: linux
      image_resource: &image 
        type: registry-image
        source:
          repository: busybox
          tag: latest
      outputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - echo "hello world" > the-artifact/message
  - task: read-the-artifact
    config:
      platform: linux
      image_resource: *image
      inputs:
      - name: the-artifact
      run:
        path: sh
        args:
        - -cx
        - cat the-artifact/message